// Generated by nitro
import type { Serialize, Simplify } from 'nitropack'
declare module 'nitropack' {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/getData': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getData').default>>>>
    }
    '/api/getLever': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getLever').default>>>>
    }
    '/api/getProduction': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/getProduction').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
  }
}
export {}